#!/bin/sh
cp /web/html/Include/Config.php.example /web/html/Include/Config.php

MYSQL_USER=$(cat /run/secrets/MYSQL_USER)
MYSQL_PASSWORD=$(cat /run/secrets/MYSQL_PASSWORD)

sed -i "s/||DB_SERVER_NAME||/$MYSQL_DB_HOST/g" /web/html/Include/Config.php
sed -i "s/||DB_NAME||/$MYSQL_DATABASE/g" /web/html/Include/Config.php
sed -i "s/||DB_USER||/$MYSQL_USER/g" /web/html/Include/Config.php
sed -i "s/||DB_PASSWORD||/$MYSQL_PASSWORD/g" /web/html/Include/Config.php
sed -i "s/||URL||//g" /web/html/Include/Config.php
sed -i "s/||ROOT_PATH||//g" /web/html/Include/Config.php

sed -i "s/upload_max_filesize = 2M/upload_max_filesize = 16M/g" /etc/php7/php.ini
sed -i "s/post_max_size = 8M/post_max_size = 32M/g" /etc/php7/php.ini

chown -R apache:www-data /web/html
