#!/bin/bash
set +e

if [ ! -f /var/www/html/Include/Config.php ]; then
  cd /tmp
  # Latest Release Including RC
  #curl -sOL "$(jq -r ".[0] | .assets[] | .browser_download_url" < <( curl -s "https://api.github.com/repos/churchCRM/CRM/releases" ))"
  # Latest Full Release
  curl -sOL "$(jq -r ".assets[] | .browser_download_url" < <( curl -s "https://api.github.com/repos/churchCRM/CRM/releases/latest" ))"
  unzip -q *.zip
  cp -Rp ./churchcrm/. /var/www/html
  rm -R churchcrm

  # Since we've already set these passwords in the env file, lets just go ahead and put them in the database and skip the setup page.
  cp /var/www/html/Include/Config.php.example /var/www/html/Include/Config.php

  sed -i "s/||DB_SERVER_NAME||/$MYSQL_DB_HOST/g" /var/www/html/Include/Config.php
  sed -i "s/||DB_NAME||/$MYSQL_DATABASE/g" /var/www/html/Include/Config.php
  sed -i "s/||DB_USER||/$MYSQL_USER/g" /var/www/html/Include/Config.php
  sed -i "s/||DB_PASSWORD||/$MYSQL_PASSWORD/g" /var/www/html/Include/Config.php
  sed -i "s/||URL||//g" /var/www/html/Include/Config.php
  sed -i "s/||ROOT_PATH||//g" /var/www/html/Include/Config.php

  chown -R apache:www-data /web/html
fi
